// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/async/actions": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "return list of supported actions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "async"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/async/message": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "send new message to browser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "async"
                ],
                "parameters": [
                    {
                        "description": "browser message",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserMessageIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserMessageOut"
                        }
                    }
                }
            }
        },
        "/api/async/sessions": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "returns active sessions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "async"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_internal_sessions.ActiveSession"
                            }
                        }
                    }
                }
            }
        },
        "/api/async/sessions/active": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "checks if session is active",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "async"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "example": "61c135fa-b604-4ff8-bebc-aefee8155219",
                        "description": "sessionID to check",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_internal_sessions.IsActive"
                        }
                    }
                }
            }
        },
        "/api/async/sessions/cleanup": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "cleans up expired sessions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "async"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/async/start": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "start browser async session for async interactions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "async"
                ],
                "parameters": [
                    {
                        "description": "run config",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.Result"
                        }
                    }
                }
            }
        },
        "/api/async/stop": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "stop browser async session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "async"
                ],
                "parameters": [
                    {
                        "description": "run config",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ControlConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserMessageOut"
                        }
                    }
                }
            }
        },
        "/api/docs": {
            "get": {
                "description": "returns documentation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "docs"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_service.Docs"
                        }
                    }
                }
            }
        },
        "/api/eke-extract": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "process a binary file uploaded directly (multipart/form-data) and return readable content.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "run"
                ],
                "parameters": [
                    {
                        "type": "file",
                        "description": "binary file bytes",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "MIME type of the file",
                        "name": "mimeType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pandoc output format (e.g. markdown)",
                        "name": "returnPandoc",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityResult"
                        }
                    }
                }
            }
        },
        "/api/extract-markdown": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "extracts markdown from a document by its URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "run"
                ],
                "parameters": [
                    {
                        "description": "run config",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ExtractMarkdownResult"
                        }
                    }
                }
            }
        },
        "/api/parse": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "parses document by its URL and returns the parsed document.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "run"
                ],
                "parameters": [
                    {
                        "description": "run config",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ParseDocResult"
                        }
                    }
                }
            }
        },
        "/api/parse-to-markdown-kv": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Parses documents (Excel: XLSX/XLSM/XLSB/XLS/XLTX/XLTM/XLT, Word: DOCX/DOC, PowerPoint: PPTX/PPT, CSV, TXT) and returns standard Markdown. For Excel files, each sheet becomes a separate section with ## heading.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parse"
                ],
                "parameters": [
                    {
                        "description": "parse config",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ParseToMarkdownResult"
                        }
                    }
                }
            }
        },
        "/api/pdf-to-images": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "converts PDF document by its URL to images and returns the URLs of the images.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "run"
                ],
                "parameters": [
                    {
                        "description": "run config",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.PdfToImagesConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.PdfToImagesResult"
                        }
                    }
                }
            }
        },
        "/api/process": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "process URL by config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "run"
                ],
                "parameters": [
                    {
                        "description": "run config",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.Result"
                        }
                    }
                }
            }
        },
        "/api/readability": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "process URL by config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "run"
                ],
                "parameters": [
                    {
                        "description": "run config",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityResult"
                        }
                    }
                }
            }
        },
        "/api/render-markdown": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "renders markdown content to HTML.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "run"
                ],
                "parameters": [
                    {
                        "description": "markdown config",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.RenderMarkdownConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.RenderMarkdownResult"
                        }
                    }
                }
            }
        },
        "/api/status": {
            "get": {
                "description": "returns documentation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "docs"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_service.Status"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Ursa-Minor-Beta_baas_internal_sessions.ActiveSession": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "string"
                },
                "browserOpts": {
                    "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserOpts"
                },
                "createdAt": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "ttlSeconds": {
                    "type": "integer"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_internal_sessions.IsActive": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.Article": {
            "type": "object",
            "properties": {
                "byline": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "excerpt": {
                    "type": "string"
                },
                "favicon": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "length": {
                    "type": "integer"
                },
                "modifiedTime": {
                    "type": "string"
                },
                "publishedTime": {
                    "type": "string"
                },
                "rawContent": {
                    "type": "string"
                },
                "siteName": {
                    "type": "string"
                },
                "textContent": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserCookie": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "httpOnly": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "secure": {
                    "type": "boolean"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserMessageIn": {
            "type": "object",
            "properties": {
                "errorOnOperationTimeout": {
                    "description": "whether to return error when a single operation times out (default: true)",
                    "type": "boolean",
                    "default": true
                },
                "operationTimeout": {
                    "description": "timeout to execute a single command (default: 20s)",
                    "type": "string",
                    "default": "20s",
                    "example": "20s"
                },
                "program": {
                    "description": "program to run (required)",
                    "type": "string"
                },
                "requestID": {
                    "description": "ID of the current request (used for internal purposes)",
                    "type": "string"
                },
                "secrets": {
                    "description": "program secrets to use (values can be obtained as getSecret('name'))",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "sessionID": {
                    "description": "sessionID to send event to",
                    "type": "string"
                },
                "stopSession": {
                    "description": "tells browser to stop session",
                    "type": "boolean",
                    "default": false,
                    "example": true
                },
                "timeout": {
                    "description": "timeout to process message",
                    "type": "string",
                    "default": "10s",
                    "example": "10s"
                },
                "values": {
                    "description": "program values to use (values can be obtained as getValue('name'))",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserMessageOut": {
            "type": "object",
            "properties": {
                "downloadedFile": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "downloadedFileName": {
                    "type": "string"
                },
                "error": {
                    "description": "error happened when running program",
                    "type": "string"
                },
                "generationInfo": {
                    "description": "metadata related to generation via LLM",
                    "type": "object",
                    "additionalProperties": {}
                },
                "log": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "meta": {
                    "description": "metadata related to processing",
                    "allOf": [
                        {
                            "$ref": "#/definitions/service.ResultMeta"
                        }
                    ]
                },
                "outHtml": {
                    "type": "string"
                },
                "readabilityArticle": {
                    "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.Article"
                },
                "requestID": {
                    "description": "ID of the current request (used for internal purposes)",
                    "type": "string"
                },
                "screenshots": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                },
                "sessionID": {
                    "description": "sessionID to send event to",
                    "type": "string"
                },
                "timestamp": {
                    "description": "timestamp of the response",
                    "type": "string"
                },
                "value": {
                    "description": "return value"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserOpts": {
            "type": "object",
            "properties": {
                "azureOpenaiApiVersion": {
                    "description": "API version for Azure OpenAI LLM client",
                    "type": "string"
                },
                "azureOpenaiDeploymentName": {
                    "description": "deployment name for Azure OpenAI LLM client",
                    "type": "string"
                },
                "azureOpenaiEndpoint": {
                    "description": "endpoint for Azure OpenAI LLM client",
                    "type": "string"
                },
                "azureOpenaiKey": {
                    "description": "API key for Azure OpenAI LLM client",
                    "type": "string"
                },
                "cookies": {
                    "description": "cookies to set before executing actions",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserCookie"
                    }
                },
                "errorOnOperationTimeout": {
                    "description": "whether to return error when a single operation times out (default: true)",
                    "type": "boolean",
                    "default": true
                },
                "headers": {
                    "description": "additional headers to set before executing actions",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "height": {
                    "description": "height of the browser window",
                    "type": "integer",
                    "default": 1080,
                    "example": 1080
                },
                "llmClient": {
                    "description": "which LLM client to use",
                    "type": "string"
                },
                "ollamaApiKey": {
                    "description": "API key for Ollama LLM client",
                    "type": "string"
                },
                "ollamaUrl": {
                    "description": "URL for Ollama LLM client",
                    "type": "string"
                },
                "openaiModel": {
                    "description": "model for OpenAI LLM client",
                    "type": "string"
                },
                "openaiOrganization": {
                    "description": "organization for OpenAI LLM client",
                    "type": "string"
                },
                "openaiToken": {
                    "description": "token for OpenAI LLM client",
                    "type": "string"
                },
                "operationTimeout": {
                    "description": "timeout to execute a single command (default: 20s)",
                    "type": "string",
                    "default": "20s",
                    "example": "20s"
                },
                "program": {
                    "description": "program to run (required)",
                    "type": "string"
                },
                "returnScreenshot": {
                    "description": "whether to return screenshot after execution",
                    "type": "boolean",
                    "default": false
                },
                "secrets": {
                    "description": "program secrets to use (values can be obtained as getSecret('name'))",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "timeout": {
                    "description": "duration string in go duration format (e.g.: 10s)",
                    "type": "string",
                    "default": "60s",
                    "example": "60s"
                },
                "useProxy": {
                    "description": "use specific proxy server (default: undefined)",
                    "type": "string"
                },
                "userAgent": {
                    "description": "use user-agent (default: undefined)",
                    "type": "string"
                },
                "values": {
                    "description": "program values to use (values can be obtained as getValue('name'))",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "waitForFileDownload": {
                    "description": "whether to wait until file is downloaded",
                    "type": "boolean",
                    "default": false
                },
                "width": {
                    "description": "width of the browser window",
                    "type": "integer",
                    "default": 1920,
                    "example": 1920
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserResponse": {
            "type": "object",
            "properties": {
                "cookies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserCookie"
                    }
                },
                "downloadedFile": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "error": {
                    "type": "string"
                },
                "generationInfo": {
                    "description": "metadata related to generation via LLM",
                    "type": "object",
                    "additionalProperties": {}
                },
                "log": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "outHtml": {
                    "type": "string"
                },
                "readabilityArticle": {
                    "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.Article"
                },
                "screenshot": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "screenshots": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                },
                "sessionID": {
                    "description": "sessionID of the browser",
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.Config": {
            "type": "object",
            "properties": {
                "browser": {
                    "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserOpts"
                },
                "hold": {
                    "description": "tells baas to hold the session and send SSE events instead of just starting and responding immediately (default: true)",
                    "type": "boolean"
                },
                "maxAttempts": {
                    "description": "max amount of attempts to fetch/process (default: 3)",
                    "type": "integer"
                },
                "sessionID": {
                    "description": "sessionID to use when running async requests (must be unique)",
                    "type": "string"
                },
                "useRandomProxy": {
                    "description": "whether to use random proxy from the configured proxy pool (default: true)",
                    "type": "boolean"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.ControlConfig": {
            "type": "object",
            "properties": {
                "sessionID": {
                    "description": "sessionID to use when running async requests (must be unique)",
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.ExtractMarkdownResult": {
            "type": "object",
            "properties": {
                "markdown": {
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.HtmlTemplate": {
            "type": "object",
            "properties": {
                "accentColor": {
                    "type": "string"
                },
                "appendHtml": {
                    "type": "string"
                },
                "companyName": {
                    "type": "string"
                },
                "companyTagline": {
                    "type": "string"
                },
                "customCss": {
                    "type": "string"
                },
                "documentTitle": {
                    "type": "string"
                },
                "fontFamily": {
                    "type": "string"
                },
                "fontSize": {
                    "type": "number"
                },
                "footerText": {
                    "type": "string"
                },
                "headerHeight": {
                    "type": "number"
                },
                "headerLogo": {
                    "type": "string"
                },
                "headerLogoHeight": {
                    "type": "number"
                },
                "headerLogoPosition": {
                    "type": "string"
                },
                "headerLogoWidth": {
                    "type": "number"
                },
                "headerText": {
                    "type": "string"
                },
                "headingFont": {
                    "type": "string"
                },
                "headingScale": {
                    "type": "number"
                },
                "margins": {
                    "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.HtmlTemplateMargins"
                },
                "prependHtml": {
                    "type": "string"
                },
                "primaryColor": {
                    "type": "string"
                },
                "secondaryColor": {
                    "type": "string"
                },
                "showPageNumbers": {
                    "type": "boolean"
                },
                "textColor": {
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.HtmlTemplateMargins": {
            "type": "object",
            "properties": {
                "bottom": {
                    "type": "number"
                },
                "left": {
                    "type": "number"
                },
                "right": {
                    "type": "number"
                },
                "top": {
                    "type": "number"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.ParseDocResult": {
            "type": "object",
            "properties": {
                "meta": {
                    "description": "metadata related to processing",
                    "allOf": [
                        {
                            "$ref": "#/definitions/service.ResultMeta"
                        }
                    ]
                },
                "result": {},
                "usedBrowser": {
                    "description": "if browser was used while processing",
                    "type": "boolean"
                },
                "usedProxy": {
                    "description": "which proxy server was used for fetching",
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.ParseToMarkdownResult": {
            "type": "object",
            "properties": {
                "markdown": {
                    "description": "markdown output",
                    "type": "string"
                },
                "meta": {
                    "description": "metadata related to processing",
                    "allOf": [
                        {
                            "$ref": "#/definitions/service.ResultMeta"
                        }
                    ]
                },
                "usedBrowser": {
                    "description": "if browser was used while processing",
                    "type": "boolean"
                },
                "usedProxy": {
                    "description": "which proxy server was used for fetching",
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.PdfToImagesConfig": {
            "type": "object",
            "properties": {
                "batchSize": {
                    "type": "integer"
                },
                "density": {
                    "type": "integer"
                },
                "outputFormat": {
                    "type": "string"
                },
                "pdfUrl": {
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.PdfToImagesResult": {
            "type": "object",
            "properties": {
                "imageUrls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityConfig": {
            "type": "object",
            "properties": {
                "URL": {
                    "description": "which URL to fetch (e.g. \"https://en.wikipedia.org/Schema_migration\")",
                    "type": "string"
                },
                "csvDelimiter": {
                    "description": "specify delimiter for CSV output (default: \",\")",
                    "type": "string"
                },
                "doNotUseCache": {
                    "description": "do not use cache when processing, always fetch fresh data",
                    "type": "boolean"
                },
                "embedResources": {
                    "description": "whether to embed resources (images, stylesheets) into the returned HTML (default: false)",
                    "type": "boolean"
                },
                "fallbackToBrowser": {
                    "description": "whether to fallback to browser if fetch didn't succeed",
                    "type": "boolean"
                },
                "forceMimeType": {
                    "description": "force specific MIME type when processing (e.g. \"application/pdf\")",
                    "type": "string"
                },
                "forcePdf": {
                    "description": "whether to convert docs to PDF before parsing",
                    "type": "boolean"
                },
                "forceUseBrowser": {
                    "description": "whether to use browser first",
                    "type": "boolean"
                },
                "headers": {
                    "description": "additional headers to send with the request",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "ignoreMimetype": {
                    "description": "ignore MIME type when processing",
                    "type": "boolean"
                },
                "maxAttempts": {
                    "description": "max amount of attempts to fetch/process (default: 3)",
                    "type": "integer"
                },
                "parseOutputFormat": {
                    "description": "specify output format for parsed documents",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.parseOutputFormat"
                        }
                    ]
                },
                "parseTableData": {
                    "description": "whether to extract table data from the document",
                    "type": "boolean"
                },
                "returnFullHtml": {
                    "description": "whether to return raw HTML output from fetch in addition to readability article (default: false)",
                    "type": "boolean"
                },
                "returnPandoc": {
                    "description": "specify one of supported pandoc formats to return HTML converted onto it in addition to readability article (default: false)",
                    "type": "string"
                },
                "timeout": {
                    "description": "overall timeout in duration format, e.g. ` + "`" + `10s` + "`" + `, cannot exceed 60s",
                    "type": "string"
                },
                "useProxy": {
                    "description": "use specific proxy in format host:port (default: undefined)",
                    "type": "string"
                },
                "useRandomProxy": {
                    "description": "whether to use random proxy from the configured proxy pool (default: false)",
                    "type": "boolean"
                },
                "userAgent": {
                    "description": "which User-Agent to set whilst fetching (default: \"*\")",
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityResult": {
            "type": "object",
            "properties": {
                "article": {
                    "description": "result of readability processing",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.Article"
                        }
                    ]
                },
                "meta": {
                    "description": "metadata related to processing",
                    "allOf": [
                        {
                            "$ref": "#/definitions/service.ResultMeta"
                        }
                    ]
                },
                "pandoc": {
                    "description": "HTML content converted to Pandoc (if requested)",
                    "type": "string"
                },
                "rawContent": {
                    "description": "raw content of the fetched URL (if requested)",
                    "type": "string"
                },
                "tables": {
                    "description": "extracted table data (if any)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityTable"
                    }
                },
                "usedBrowser": {
                    "description": "if browser was used while processing",
                    "type": "boolean"
                },
                "usedProxy": {
                    "description": "which proxy server was used for fetching",
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.ReadabilityTable": {
            "type": "object",
            "properties": {
                "headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {}
                    }
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.RenderMarkdownConfig": {
            "type": "object",
            "properties": {
                "markdown": {
                    "type": "string"
                },
                "outputFormat": {
                    "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.outputFormat"
                },
                "preprocessMath": {
                    "type": "boolean"
                },
                "scaleFactor": {
                    "type": "number"
                },
                "template": {
                    "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.HtmlTemplate"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.RenderMarkdownResult": {
            "type": "object",
            "properties": {
                "html": {
                    "type": "string"
                },
                "outputUrl": {
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.Result": {
            "type": "object",
            "properties": {
                "meta": {
                    "description": "metadata related to processing",
                    "allOf": [
                        {
                            "$ref": "#/definitions/service.ResultMeta"
                        }
                    ]
                },
                "result": {
                    "description": "result returned by browser",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Ursa-Minor-Beta_baas_pkg_dto.BrowserResponse"
                        }
                    ]
                },
                "usedProxy": {
                    "description": "which proxy server was used for fetching",
                    "type": "string"
                }
            }
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.outputFormat": {
            "type": "string",
            "enum": [
                "html",
                "pdf",
                "docx"
            ],
            "x-enum-varnames": [
                "Html",
                "Pdf",
                "Docx"
            ]
        },
        "github_com_Ursa-Minor-Beta_baas_pkg_dto.parseOutputFormat": {
            "type": "string",
            "enum": [
                "markdown",
                "json"
            ],
            "x-enum-varnames": [
                "Markdown",
                "Json"
            ]
        },
        "internal_service.BaasStatus": {
            "type": "object",
            "properties": {
                "aipandocCommit": {
                    "type": "string"
                },
                "browserStatus": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_service.Docs": {
            "type": "object",
            "properties": {
                "commands": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "commandsJSON": {
                    "type": "string"
                }
            }
        },
        "internal_service.Status": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/service.ResultMeta"
                },
                "status": {
                    "$ref": "#/definitions/internal_service.BaasStatus"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "service.ResultMeta": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "error": {
                    "description": "whether error happened whilst processing",
                    "type": "string"
                },
                "isAuthorized": {
                    "type": "boolean"
                },
                "requestFinishedAt": {
                    "type": "string"
                },
                "requestStartedAt": {
                    "type": "string"
                },
                "requestTime": {
                    "$ref": "#/definitions/time.Duration"
                },
                "requestUID": {
                    "description": "unique identifier of job for debugging purposes",
                    "type": "string"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000,
                1,
                1000,
                1000000,
                1000000000,
                1,
                1000,
                1000000,
                1000000000,
                60000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute"
            ]
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and API token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
